### ISSUE TITLE
Multiple page opening when clicking on markers that are superimposed on each other

### ISSUE THREAD

**Issue by alexeydolmatov** [Unact/yandex_mapkit#62] opened 2020-10-16 23:11 UTC
When I place two markers close to each other, and they overlap each other (intersect with each other), and each of them has a click handler in the form of opening a window with detailed information about the object that the marker corresponds to, then two windows open at once

**Comment by DCrow** [comment] 2020-10-19 08:02
Hello!

As far as I know this is something that you have to resolve yourself in your application. 
Click handlers are called from native code, so this is intended behavior.

**Comment by alexeydolmatov** [comment] 2020-10-19 23:07
I expect that only the window with the corresponding marker on top of the others should open

**Comment by DCrow** [comment] 2020-11-09 08:09
This is something that must be resolved in your application.

Or you can ask the same question in parent [iOS](https://github.com/yandex/mapkit-ios-demo/issues?page=3&q=is%3Aissue+is%3Aclosed)/[Android](https://github.com/yandex/mapkit-android-demo) libraries.

**Closed by DCrow** 2020-11-09 08:09 UTC
Labels: question
