### ISSUE TITLE
Memory Leak on Android 

### ISSUE THREAD

**Issue by topor00** [Unact/yandex_mapkit#89] opened 2021-02-18 14:01 UTC
I have memory leak on Android device in this case: when I add many Placemarks to YandexMapController  and dispose() class after that. After that new open class and add this placemarks again to YandexMapController and dispose() class again . Repeat this some times and have error "JNI ERROR (app bug): global reference table overflow (max=51200)global reference table dump:" and application crashes. I have no any errors on iOS devices

**Comment by DCrow** [comment] 2021-02-19 07:53
Hello!

Please provide your `flutter doctor --verbose`, `pubspec.yaml` and a log of your error.
If possible also an example app which reproduces your problem would be very helpful.

**Comment by DCrow** [comment] 2021-04-01 10:19
Closing since my previous question hasn't been answered.

**Closed by DCrow** 2021-04-01 10:19 UTC
Labels: question
