### ISSUE TITLE
Map crash 

### ISSUE THREAD

**Issue by just-kip** [Unact/yandex_mapkit#49] opened 2020-05-20 07:00 UTC
Guys,
Please have a look at the video: 
https://drive.google.com/file/d/1dr1Ffqe2qroXqC5b4gzpsBYljNZvALFg/view

I slightly modified example app to demo the crash. 

There are no crash reports. Profiler says the app consumes roughly 30MB memory.
I checked native code and didn't found any issues, everything seems to be correct.

If I add objects on map, e.g. custom placemark icons crashes occur more often.
Any ideas on what goes wrong or how to overcome the issue are greatly appreciated.

**Comment by DCrow** [comment] 2020-05-21 07:35
Please provide your `flutter run --verbose`, `flutter doctor -v` and a copy of your `pubspec.yml` since it might be caused by some other library.
It would be great if you could also provide a minimum code sample or the steps to reproduce your problem. 

Also the video is not public so nobody can watch it

**Comment by just-kip** [comment] 2020-05-21 11:12
@DCrow, 
I've just checked the video in chrome "incognito" window - it's publically available. Please have a look once again.
The `minimum code sample` is the demo from this repo. However, make sure to run it on a device, since the issue may be hard to reproduce on a simulator. E.g. there is iPhone 6 Plus on the video. I also tried iPhone 6 & iPhone 8.
The app was built with flutter versions `1.12.13+hotfix.5` and `1.12.13+hotfix.8`.
Here is part of log from our CI which shows flutter version:
``
$ cd ~/.flutter_sdk/flutter && git fetch && git checkout v1.12.13+hotfix.5
▸ Previous HEAD position was f139b1100 update to engine hash that includes Dart 2.7.2 (#53591)
▸ HEAD is now at 27321ebba v1.12.13+hotfix.5 cherry-picks (#46726)(#46726)
``
I'll try to reproduce the issue with `flutter run --verbose` and attach the log.

**Comment by DCrow** [comment] 2020-05-21 12:43
Yes, now the video is accessible for me.

As for the problem, I can also reproduce this issue. 
Even without adding any `mapObject` to `YandexMap` it will still eventually crash. 
Every new page with YMKMapView increases used memory but on page close the used memory doesn't get freed.

This seems to be a flutter platforms bug. As I can see there is a similar bug https://github.com/flutter/flutter/issues/45697

This can be fixed only on flutter's side, since it doesn't clear the native view correctly.

**Closed by DCrow** 2020-05-21 12:43 UTC

**Comment by shorben07** [comment] 2020-05-21 13:02
There is a workaround for out of memory crashes. Use a wrapper view
```
class MapPlatformView: NSObject, FlutterPlatformView {
    
    let wrapperView: UIView
    let interactiveMap: YandexMap

    func view() -> UIView {
        return wrapperView
    }
    
    init(withFrame frame: CGRect,
         viewIdentifier viewId: Int64,
         arguments args: Any?,
         registrar: FlutterPluginRegistrar) {

        wrapperView = UIView(frame: frame)
        interactiveMap = YandexMap(withFrame: frame)

        super.init()
       //TODO: add constraints
        wrapperView.addSubView(interactiveMap.view)
    }
    
    deinit {
        interactiveMap.view.removeFromSuperview()
    }
}
```

**Comment by DCrow** [comment] 2020-05-21 13:17
@shorben07 Does this really work? Why should wrapping a view in another view suddenly help? 

The main problem here is that when the corresponding flutter view is destroyed, the ios view is still retained in memory.

**Comment by shorben07** [comment] 2020-05-21 13:47
MapPlatformView **is** destroyed. But view returned in the method `func view() -> UIView` is not.
So, yes `wrapperView` is retained in memory but at least we removed and destroyed `interactiveMap` in `deinit`

**Comment by DCrow** [comment] 2020-05-21 14:23
I guess this really helps for views with a large memory footprint, but it still doesn't resolve the memory problem, since `wrapperView` is still in memory and after a while will also lead to a memory crash.

**Comment by just-kip** [comment] 2020-05-21 14:57
@shorben07 Thank you a lot! You workaround resolves my issue.
